<?php

return [
    'profile' => [
        'name' => 'Yara Nashef',
        'title' => 'Fresh Graduate Architecture Engineer',
        'tagline' => 'Architecture as a Journey to Healing',
        'location' => 'Nof HaGalil, Israel',
        'phone' => '+972 0532498554',
        'phone_href' => '+972532498554',
        'email' => 'yaranasheff@gmail.com',
        'linkedin' => 'https://www.linkedin.com/in/yara-nashef-32b952216/',
        'years' => '2021 — 2026',
        'about' => 'Yara Nashef is a dedicated and skill-driven Architectural Engineering graduate based in Jordan. Known for her precision, creativity, and strong work ethic, she consistently demonstrates a balance between technical understanding and design awareness. Yara excels in collaborative settings, adapts quickly to challenges, and approaches every task with focus, responsibility, and a drive for excellence.',
        'languages' => [
            ['name' => 'Arabic', 'level' => 'Native'],
            ['name' => 'English', 'level' => 'Fluent'],
            ['name' => 'Hebrew', 'level' => 'Fluent'],
        ],
    ],

    'experience' => [
        [
            'role' => 'Intern Architect',
            'place' => "Tha'er Qub'a Consultant Architects",
            'dates' => 'Jul — Sep 2025',
            'city' => 'Amman, Jordan',
            'text' => "Oversaw the continuation and development of ongoing projects, while contributing to the office's participation in the Tamayouz Excellence Award.",
            'featured' => true,
        ],
    ],

    'education' => [
        [
            'title' => 'Bachelor of Architecture Engineering',
            'place' => 'University of Jordan',
            'dates' => '2021 — 2026',
            'city' => 'Amman, Jordan',
        ],
        [
            'title' => 'Christ Anglican School',
            'place' => 'Secondary Education',
            'dates' => '2020',
            'city' => 'Nazareth, Israel',
        ],
    ],

    'certifications' => [
        [
            'title' => 'OMNIPLAN Training Course',
            'tools' => 'Revit, Photoshop, AutoCAD, 3D Max, Lumion, V-Ray, D5, Enscape',
            'points' => [
                'Developed high-quality architectural visualizations integrating Revit models with Lumion rendering and Photoshop post-processing.',
                'Improved efficiency in BIM-based design and presentation workflows.',
                'Highly proficient in producing photorealistic renderings and animations using D5 Render, Enscape, and Lumion.',
                'Skilled at optimizing lighting, materials, and camera settings to achieve visually compelling architectural visualizations.',
            ],
        ],
    ],

    'skills' => [
        ['name' => 'Revit', 'group' => 'BIM', 'text' => 'BIM modeling, documentation, and coordinated design workflows.'],
        ['name' => 'AutoCAD', 'group' => 'Drafting', 'text' => 'Precise 2D drafting for plans, sections, and construction sets.'],
        ['name' => '3D Max', 'group' => 'Modeling', 'text' => 'Detailed modeling for complex forms and presentation scenes.'],
        ['name' => 'Enscape', 'group' => 'Realtime', 'text' => 'Live walkthroughs and rapid design communication.'],
        ['name' => 'D5 Render', 'group' => 'Visuals', 'text' => 'Photoreal lighting, materials, and cinematic stills.'],
        ['name' => 'Lumion', 'group' => 'Visuals', 'text' => 'Atmospheric animations and large-site storytelling.'],
        ['name' => 'Adobe Suite', 'group' => 'Graphic', 'text' => 'Photoshop post-process, layout, and visual identity.'],
        ['name' => 'V-Ray', 'group' => 'Visuals', 'text' => 'Controlled lighting and material fidelity for stills.'],
    ],

    'soft' => [
        'Creative problem solving',
        'Time management',
        'Teamwork',
        'Attention to detail',
    ],

    'projects' => [
        [
            'slug' => 'sukoon-ptsd-healing-center',
            'code' => '01',
            'title' => 'Sukoon PTSD Healing Center',
            'short' => 'Grad Project — Thesis',
            'place' => 'Dead Sea, Amman — Jordan',
            'studio' => 'Supervised by Dr. Feras Sharaf',
            'year' => '2026',
            'cover' => '15.jpeg',
            'logo' => '1.jpg',
            'hero' => true,
            'featured' => true,
            'quote' => 'At the Lowest Point, Toward a New Beginning',
            'concept' => 'Architecture as a Journey to Healing',
            'excerpt' => 'A holistic healing sanctuary at the Dead Sea, where architecture itself becomes an active participant in trauma recovery.',
            'body' => [
                'By utilizing the Healing through Nature approach, Sukoon leverages its extraordinary location at the Dead Sea in Jordan. As the lowest point on Earth, the site offers unique therapeutic qualities, including oxygen-rich air and mineral-dense waters. Its position at the closest point to the Palestinian border also ensures symbolic resonance and ease of accessibility for those most affected by regional trauma.',
                'The primary goal of Sukoon is to fill the existing healthcare gap by providing a facility that caters to the complex needs of PTSD patients, individuals with general mental health issues, and people with physical disabilities.',
                'The objectives include the design of a barrier-free environment that promotes inclusivity and the integration of remarkable views and natural elements to reduce patient anxiety. By harmonizing the built environment with the therapeutic landscape of the Dead Sea, the project aims to establish a new architectural precedent for trauma-informed design in the region.',
                'The Middle East has long been a region marked by conflict, leaving behind a profound need for specialized care that addresses both the visible and invisible scars of war. Sukoon is envisioned as a holistic healing center dedicated to survivors of Post-Traumatic Stress Disorder, offering a sanctuary for both mental and physical rehabilitation.',
            ],
            'gallery' => [4, 5, 15, 13, 16, 6, 7, 8, 9, 10, 11, 12, 14, 17, 18, 19, 20, 21, 22, 34],
        ],
        [
            'slug' => 'vault-veil-boutique-hotel',
            'code' => '02',
            'title' => 'Vault & Veil Boutique Hotel',
            'short' => 'Design Studio 6',
            'place' => 'Iraq Al Amir, Amman — Jordan',
            'studio' => 'Supervised by Dr. Nancy Al Assaf',
            'year' => '2025',
            'cover' => '23.jpeg',
            'logo' => '2.jpeg',
            'hero' => true,
            'featured' => true,
            'quote' => 'Bridging Time Through Space And Light',
            'concept' => 'Layers of Memory: A Dialogue Between Past and Present',
            'excerpt' => 'An adaptive-reuse boutique hotel that frames historic stone houses with floating roofs, steel, and timber.',
            'body' => [
                'Set in the culturally rich landscape of Iraq Al-Amir, this boutique hotel emerges as a contemporary reinterpretation of the site\'s layered history. Rooted in the principles of adaptive reuse, the design preserves and integrates existing heritage structures—echoes of a vernacular past—within a bold architectural language of intersecting planes and voids.',
                'Inspired by the timeless presence of the Qasr al-Abd and the carved caves nearby, the hotel acts as a spatial palimpsest: where new geometries hover, frame, and embrace the old.',
                'This boutique hotel transforms a group of historic stone houses into a modern retreat. By preserving the original walls and introducing exposed steel and timber trusses, the design blends tradition with contemporary lightness. New roofs float above the old structures, while courtyards and stepped paths connect the rooms across the terraced site.',
            ],
            'gallery' => [23, 28, 24, 25, 26, 27, 29, 30, 31, 32, 33],
        ],
        [
            'slug' => 'excellence-center',
            'code' => '03',
            'title' => 'Excellence Center — JU',
            'short' => 'Design Studio 4',
            'place' => 'University of Jordan, Amman',
            'studio' => 'Supervised by Dr. Lamees Shaaban',
            'year' => '2024',
            'cover' => '44.jpeg',
            'logo' => '3.jpeg',
            'hero' => true,
            'featured' => false,
            'quote' => 'Unity through Fluid Massing',
            'concept' => 'An interconnected campus of collaboration',
            'excerpt' => 'A dynamic excellence center of varying heights, bound by unity, fluidity, and a post-tension structure.',
            'body' => [
                'The concept of the Design Excellence Center revolves around creating an interconnected, dynamic space that fosters collaboration, innovation, and creativity through a cohesive arrangement of masses with varying heights, inspired by the idea of unity and fluidity.',
                'The structural system is post-tension, allowing long spans, open collaborative floors, and a precise dialogue between mass and void across the university campus.',
            ],
            'gallery' => [44, 45, 50, 35, 36, 37, 38, 39, 40, 41, 42, 43, 46, 47, 48, 49, 51, 52, 53, 54],
        ],
        [
            'slug' => 'agriculture-research-center',
            'code' => '04',
            'title' => 'Agriculture Research Center',
            'short' => 'Design Studio 5',
            'place' => 'University of Jordan, Amman',
            'studio' => 'Supervised by Dr. Khalid Al Omari',
            'year' => '2024',
            'cover' => '55.jpeg',
            'logo' => '4.jpeg',
            'hero' => true,
            'featured' => false,
            'quote' => 'Freedom and Rule',
            'concept' => 'Circle and square, curve and straight',
            'excerpt' => 'A research campus built on the tension between circle and square — freedom held by rule.',
            'body' => [
                'The relation between circle and square, curve and straight, freedom and rule, can be found as well in the contrast between the two main architectural elements.',
                'A circular courtyard with a living tree becomes the quiet heart of a precise rectangular massing, organizing laboratories, administration, and landscape into a single research organism.',
            ],
            'gallery' => [55, 56, 57, 58, 59, 60],
        ],
        [
            'slug' => 'public-library',
            'code' => '05',
            'title' => 'Public Library',
            'short' => 'Design Studio 3',
            'place' => 'Sport City, Amman — Jordan',
            'studio' => 'Supervised by Dr. Lamees Shaaban',
            'year' => '2023',
            'cover' => '61.jpeg',
            'logo' => '5.jpeg',
            'hero' => false,
            'featured' => false,
            'quote' => 'Cluster, Grid, and Path',
            'concept' => 'Cubism as a public civic form',
            'excerpt' => 'A clustered public library inspired by Cubism, held together by a functional grid and a continuous pathway.',
            'body' => [
                'The main element used in the design is a grid to help the clustering stay functional. Clustered architecture is beautiful yet challenging, which is why the Cubism school inspired the design.',
                'The building mingles with its surroundings through material. One of the hardest and most essential ambitions was to create and maintain a pathway through such a clustered building.',
                'A public library must remain functional. Gradation was added so the concept could live without losing civic clarity.',
            ],
            'gallery' => [61, 67, 62, 63, 64, 65, 66, 68, 69, 70, 71],
        ],
        [
            'slug' => 'sketches',
            'code' => '06',
            'title' => 'Sketches',
            'short' => 'Hand Studies',
            'place' => 'Selected Drawings',
            'studio' => 'Personal Work',
            'year' => '2021 — 2026',
            'cover' => '76.jpeg',
            'logo' => null,
            'hero' => false,
            'featured' => false,
            'quote' => 'Line before mass',
            'concept' => 'Observation, memory, and hand',
            'excerpt' => 'A selection of architectural sketches — observation, travel, and the first mark of every project.',
            'body' => [
                'A quiet collection of hand drawings that sit beside the built work: cathedrals, massing studies, and the first lines that later become plans, sections, and light.',
            ],
            'gallery' => [72, 73, 74, 75, 76, 77, 78],
        ],
    ],
];
